# Generated by Django 4.2.23 on 2025-06-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_info", models.TextField()),
                ("metrics_info", models.TextField()),
                ("log_info", models.TextField()),
                ("analysis_result", models.TextField()),
                ("solution", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge_base.faultcategory",
                    ),
                ),
                (
                    "matched_knowledge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge_base.faultknowledge",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Fault Cases",},
        ),
    ]
